version: '3.8'

services:
  user-mysqldb:
    container_name: user_mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dealshop_user
      TZ: Asia/Seoul
    ports:
      - 3308:3306

  product-mysqldb:
    container_name: product_mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dealshop_product
      TZ: Asia/Seoul
    ports:
      - 3309:3306

  order-mysqldb:
    container_name: order_mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dealshop_order
      TZ: Asia/Seoul
    ports:
      - 3310:3306

  payment-mysqldb:
    container_name: payment_mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dealshop_payment
      TZ: Asia/Seoul
    ports:
      - 3311:3306

  user-redis:
    container_name: user_redis
    image: redis
    ports:
      - "6380:6379"

  stock-redis:
    container_name: stock_redis
    image: redis
    ports:
      - "6381:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper