version: '3.8'

services:
  user-mysqldb:
    container_name: user_mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user
      TZ: Asia/Seoul
    ports:
      - 3308:3306
  user-redis:
    container_name: user_redis
    image: redis
    ports:
      - "6380:6379"