spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${database.password}
  data:
    redis:
      host: localhost
      port: 6380
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${dealshop.mail.username}
    password: ${dealshop.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30분